import { STATUS } from '@hydrooj/common';

export function normalize(key: string) {
    return key.toUpperCase().replace(/[ _-]/g, '');
}

function removeSlash(src: Record<string, STATUS>) {
    const dst = {};
    for (const key of Object.keys(src)) dst[key.replace(/_/g, '')] = src[key];
    return dst;
}

const YACS_VERDICT: Record<string, STATUS> = {
    '\u6b63\u5728\u8bc4\u6d4b': STATUS.STATUS_JUDGING,
    '\u7b54\u6848\u6b63\u786e': STATUS.STATUS_ACCEPTED,
    '\u7f16\u8bd1\u5931\u8d25': STATUS.STATUS_COMPILE_ERROR,
    '\u90e8\u5206\u6b63\u786e': STATUS.STATUS_WRONG_ANSWER,
    '\u8fd0\u884c\u8d85\u65f6': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    '\u5185\u5b58\u8d85\u51fa': STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    '\u6682\u672a\u516c\u5e03': STATUS.STATUS_SYSTEM_ERROR,
    '\u8bc4\u6d4b\u673a\u6545\u969c': STATUS.STATUS_SYSTEM_ERROR,
};

const HUSTOJ_VERDICT: Record<string, STATUS> = {
    '\u7b49\u5f85': STATUS.STATUS_WAITING,
    '\u8fd0\u884c\u5e76\u8bc4\u5224': STATUS.STATUS_JUDGING,
    '\u6b63\u5728\u8bc4\u6d4b\u4e2d': STATUS.STATUS_JUDGING,
    '\u7f16\u8bd1\u6210\u529f': STATUS.STATUS_JUDGING,
    '\u6b63\u786e': STATUS.STATUS_ACCEPTED,
    '\u683c\u5f0f\u9519\u8bef': STATUS.STATUS_WRONG_ANSWER,
    '\u7b54\u6848\u9519\u8bef': STATUS.STATUS_WRONG_ANSWER,
    '\u8f93\u51fa\u8d85\u9650': STATUS.STATUS_WRONG_ANSWER,
    '\u8fd0\u884c\u65f6\u9519\u8bef': STATUS.STATUS_RUNTIME_ERROR,
    '\u65f6\u95f4\u8d85\u9650': STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    '\u5185\u5b58\u8d85\u9650': STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    '\u7f16\u8bd1\u9519\u8bef': STATUS.STATUS_COMPILE_ERROR,
    '\u672a\u77e5\u9519\u8bef': STATUS.STATUS_SYSTEM_ERROR,
};

export const VERDICT = new Proxy<Record<string, STATUS>>(removeSlash({
    RUNTIME_ERROR: STATUS.STATUS_RUNTIME_ERROR,
    WRONG_ANSWER: STATUS.STATUS_WRONG_ANSWER,
    OK: STATUS.STATUS_ACCEPTED,
    COMPILING: STATUS.STATUS_COMPILING,
    TIME_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEEDED: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    IDLENESS_LIMIT_EXCEEDED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    ACCEPTED: STATUS.STATUS_ACCEPTED,
    PRESENTATION_ERROR: STATUS.STATUS_WRONG_ANSWER,
    OUTPUT_LIMIT_EXCEEDED: STATUS.STATUS_OUTPUT_LIMIT_EXCEEDED,
    EXTRA_TEST_PASSED: STATUS.STATUS_ACCEPTED,
    COMPILE_ERROR: STATUS.STATUS_COMPILE_ERROR,
    'RUNNING_&_JUDGING': STATUS.STATUS_JUDGING,
    QUEUING: STATUS.STATUS_WAITING,
    RUNNING: STATUS.STATUS_JUDGING,

    // Codeforces
    'HAPPY_NEW_YEAR!': STATUS.STATUS_ACCEPTED,

    // Vjudge
    QUEUEING: STATUS.STATUS_COMPILING,
    PENDING: STATUS.STATUS_COMPILING,
    SUBMITTED: STATUS.STATUS_COMPILING,
    JUDGING: STATUS.STATUS_JUDGING,
    AC: STATUS.STATUS_ACCEPTED,
    WA: STATUS.STATUS_WRONG_ANSWER,
    RE: STATUS.STATUS_RUNTIME_ERROR,
    CE: STATUS.STATUS_COMPILE_ERROR,
    PE: STATUS.STATUS_WRONG_ANSWER,
    TLE: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MLE: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    OLE: STATUS.STATUS_WRONG_ANSWER,
    FAILED_OTHER: STATUS.STATUS_SYSTEM_ERROR,
    SUBMIT_FAILED_PERM: STATUS.STATUS_SYSTEM_ERROR,
    SUBMIT_FAILED_TEMP: STATUS.STATUS_SYSTEM_ERROR,

    // YACS
    ...YACS_VERDICT,

    // HustOJ
    WAITING: STATUS.STATUS_WAITING,
    RUNNING_JUDGING: STATUS.STATUS_JUDGING,
    OUTPUT_LIMIT_EXCEED: STATUS.STATUS_WRONG_ANSWER,
    DANGEROUS_SYSCALL: STATUS.STATUS_RUNTIME_ERROR,
    TIME_LIMIT_EXCEED: STATUS.STATUS_TIME_LIMIT_EXCEEDED,
    MEMORY_LIMIT_EXCEED: STATUS.STATUS_MEMORY_LIMIT_EXCEEDED,
    COMPILATION_ERROR: STATUS.STATUS_COMPILE_ERROR,
    RF: STATUS.STATUS_SYSTEM_ERROR,
    SYSTEM_ERROR: STATUS.STATUS_SYSTEM_ERROR,
    SE: STATUS.STATUS_SYSTEM_ERROR,
    ...HUSTOJ_VERDICT,
}), {
    get(self, key) {
        if (typeof key === 'symbol') return null;
        key = normalize(key);
        if (typeof STATUS[key] === 'number') return STATUS[key];
        if (typeof self[key] === 'number') return self[key];
        return null;
    },
});
