$env:HYDRO_SUBMISSION_AI_PROVIDER="kaggle"
$env:HYDRO_KAGGLE_KERNEL_ID="tranducngan/atcv1"
$env:HYDRO_KAGGLE_ATC_DATASET_SOURCE="tranducngan/atcv1-source"
$env:HYDRO_KAGGLE_ATC_PREBUILT_PATH="/kaggle/input/datasets/tranducngan/atcv1-source/ATC-main"
$env:HYDRO_KAGGLE_ATC_PROJECT_DIR="ATC-main"
$env:HYDRO_KAGGLE_EXTRA_DATASET_SOURCES="your-kaggle-username/codellama-7b-instruct-hf,your-kaggle-username/p100-torch-cu124-wheels"
$env:HYDRO_KAGGLE_P100_TORCH_WHEEL_PATH="/kaggle/input/p100-torch-cu124-wheels/wheels"
$env:HYDRO_KAGGLE_ATC_BASE_MODEL="/kaggle/input/codellama-7b-instruct-hf"
$env:HYDRO_KAGGLE_ENABLE_INTERNET="false"
$env:HYDRO_KAGGLE_INSTALL_P100_TORCH="true"
$env:HYDRO_KAGGLE_ATC_METHOD="entropy"
$env:HYDRO_KAGGLE_ATC_DEVICE="auto"
$env:HYDRO_KAGGLE_ATC_ALLOW_CPU_FALLBACK="true"
$env:HYDRO_KAGGLE_ATC_INFER_TASK="true"
$env:HYDRO_KAGGLE_ATC_PROMPT_STYLE="regular"
$env:HYDRO_KAGGLE_ATC_PATTERN_WEIGHTS="comments:0,docstrings:0"
$env:HYDRO_KAGGLE_ATC_THRESHOLD="-0.185"
$env:HYDRO_KAGGLE_ATC_MIN_NONEMPTY_LINES="8"
$env:HYDRO_KAGGLE_ATC_MIN_NONWHITESPACE_CHARS="120"
$env:HYDRO_KAGGLE_POLL_INTERVAL_MS="5000"
$env:HYDRO_KAGGLE_TIMEOUT_MS="0"

cd C:\DATN\test\Hydro-master
corepack yarn dev:judge:kaggle-ai
