import {
    getScoreColor, NORMAL_STATUS, PERM, PRIV, STATUS, STATUS_CODES, STATUS_SHORT_TEXTS,
    STATUS_TEXTS, USER_GENDER_FEMALE, USER_GENDER_ICONS, USER_GENDER_MALE,
    USER_GENDER_OTHER, USER_GENDER_RANGE, USER_GENDERS,
} from '@hydrooj/common';

export * from '@hydrooj/common/permission';
export * from '@hydrooj/common/status';

export const Permission = (family: string, key: bigint, desc: string) => ({ family, key, desc });

export const PERMS = [
    Permission('perm_general', PERM.PERM_VIEW, 'View this domain'),
    Permission('perm_general', PERM.PERM_VIEW_USER_PRIVATE_INFO, 'View domain user private info'),
    Permission('perm_general', PERM.PERM_EDIT_DOMAIN, 'Edit domain settings'),
    Permission('perm_general', PERM.PERM_MOD_BADGE, 'Show MOD badge'),
    Permission('perm_problem', PERM.PERM_CREATE_PROBLEM, 'Create problems'),
    Permission('perm_problem', PERM.PERM_EDIT_PROBLEM, 'Edit problems'),
    Permission('perm_problem', PERM.PERM_EDIT_PROBLEM_SELF, 'Edit own problems'),
    Permission('perm_problem', PERM.PERM_VIEW_PROBLEM, 'View problems'),
    Permission('perm_problem', PERM.PERM_VIEW_PROBLEM_HIDDEN, 'View hidden problems'),
    Permission('perm_problem', PERM.PERM_SUBMIT_PROBLEM, 'Submit problem'),
    Permission('perm_problem', PERM.PERM_READ_PROBLEM_DATA, 'Read data of problem'),
    Permission('perm_record', PERM.PERM_VIEW_RECORD, "View other's records"),
    Permission('perm_record', PERM.PERM_READ_RECORD_CODE, 'Read all record codes'),
    Permission('perm_record', PERM.PERM_READ_RECORD_CODE_ACCEPT, 'Read record codes after accept'),
    Permission('perm_record', PERM.PERM_REJUDGE_PROBLEM, 'Rejudge problems'),
    Permission('perm_record', PERM.PERM_REJUDGE, 'Rejudge records'),
    Permission('perm_problem_solution', PERM.PERM_VIEW_PROBLEM_SOLUTION, 'View problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_VIEW_PROBLEM_SOLUTION_ACCEPT, 'View problem solutions after accept'),
    Permission('perm_problem_solution', PERM.PERM_CREATE_PROBLEM_SOLUTION, 'Create problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_VOTE_PROBLEM_SOLUTION, 'Vote problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_EDIT_PROBLEM_SOLUTION, 'Edit problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_EDIT_PROBLEM_SOLUTION_SELF, 'Edit own problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_DELETE_PROBLEM_SOLUTION, 'Delete problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_DELETE_PROBLEM_SOLUTION_SELF, 'Delete own problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_REPLY_PROBLEM_SOLUTION, 'Reply problem solutions'),
    Permission('perm_problem_solution', PERM.PERM_EDIT_PROBLEM_SOLUTION_REPLY_SELF, 'Edit own problem solution replies'),
    Permission('perm_problem_solution', PERM.PERM_DELETE_PROBLEM_SOLUTION_REPLY, 'Delete problem solution replies'),
    Permission('perm_problem_solution', PERM.PERM_DELETE_PROBLEM_SOLUTION_REPLY_SELF, 'Delete own problem solution replies'),
    Permission('perm_discussion', PERM.PERM_VIEW_DISCUSSION, 'View discussions'),
    Permission('perm_discussion', PERM.PERM_CREATE_DISCUSSION, 'Create discussions'),
    Permission('perm_discussion', PERM.PERM_HIGHLIGHT_DISCUSSION, 'Highlight discussions'),
    Permission('perm_discussion', PERM.PERM_PIN_DISCUSSION, 'Pin discussions'),
    Permission('perm_discussion', PERM.PERM_EDIT_DISCUSSION, 'Edit discussions'),
    Permission('perm_discussion', PERM.PERM_EDIT_DISCUSSION_SELF, 'Edit own discussions'),
    Permission('perm_discussion', PERM.PERM_LOCK_DISCUSSION, 'Lock discussions'),
    Permission('perm_discussion', PERM.PERM_DELETE_DISCUSSION, 'Delete discussions'),
    Permission('perm_discussion', PERM.PERM_DELETE_DISCUSSION_SELF, 'Delete own discussions'),
    Permission('perm_discussion', PERM.PERM_REPLY_DISCUSSION, 'Reply discussions'),
    Permission('perm_discussion', PERM.PERM_ADD_REACTION, 'React to discussion'),
    Permission('perm_discussion', PERM.PERM_EDIT_DISCUSSION_REPLY_SELF, 'Edit own discussion replies'),
    Permission('perm_discussion', PERM.PERM_DELETE_DISCUSSION_REPLY, 'Delete discussion replies'),
    Permission('perm_discussion', PERM.PERM_DELETE_DISCUSSION_REPLY_SELF, 'Delete own discussion replies'),
    Permission('perm_discussion', PERM.PERM_DELETE_DISCUSSION_REPLY_SELF_DISCUSSION, 'Delete discussion replies of own discussion'),
    Permission('perm_contest', PERM.PERM_VIEW_CONTEST, 'View contests'),
    Permission('perm_contest', PERM.PERM_VIEW_CONTEST_SCOREBOARD, 'View contest scoreboard'),
    Permission('perm_contest', PERM.PERM_VIEW_CONTEST_HIDDEN_SCOREBOARD, 'View hidden contest submission status and scoreboard'),
    Permission('perm_contest', PERM.PERM_CREATE_CONTEST, 'Create contests'),
    Permission('perm_contest', PERM.PERM_ATTEND_CONTEST, 'Attend contests'),
    Permission('perm_contest', PERM.PERM_EDIT_CONTEST, 'Edit any contests'),
    Permission('perm_contest', PERM.PERM_EDIT_CONTEST_SELF, 'Edit own contests'),
    Permission('perm_contest', PERM.PERM_VIEW_HIDDEN_CONTEST, 'View all contests'),
    Permission('perm_homework', PERM.PERM_VIEW_HOMEWORK, 'View homework'),
    Permission('perm_homework', PERM.PERM_VIEW_HOMEWORK_SCOREBOARD, 'View homework scoreboard'),
    Permission('perm_homework', PERM.PERM_VIEW_HOMEWORK_HIDDEN_SCOREBOARD, 'View hidden homework submission status and scoreboard'),
    Permission('perm_homework', PERM.PERM_CREATE_HOMEWORK, 'Create homework'),
    Permission('perm_homework', PERM.PERM_ATTEND_HOMEWORK, 'Claim homework'),
    Permission('perm_homework', PERM.PERM_EDIT_HOMEWORK, 'Edit any homework'),
    Permission('perm_homework', PERM.PERM_EDIT_HOMEWORK_SELF, 'Edit own homework'),
    Permission('perm_homework', PERM.PERM_VIEW_HIDDEN_HOMEWORK, 'View all homework'),
    Permission('perm_training', PERM.PERM_VIEW_TRAINING, 'View training plans'),
    Permission('perm_training', PERM.PERM_CREATE_TRAINING, 'Create training plans'),
    Permission('perm_training', PERM.PERM_EDIT_TRAINING, 'Edit training plans'),
    Permission('perm_training', PERM.PERM_PIN_TRAINING, 'Pin training plans'),
    Permission('perm_training', PERM.PERM_EDIT_TRAINING_SELF, 'Edit own training plans'),
    Permission('perm_ranking', PERM.PERM_VIEW_RANKING, 'View ranking'),
];

export const PERMS_BY_FAMILY = {};
for (const p of PERMS) {
    if (!PERMS_BY_FAMILY[p.family]) PERMS_BY_FAMILY[p.family] = [p];
    else PERMS_BY_FAMILY[p.family].push(p);
}

// people whose rank is less than 1% will get Level 10
export const LEVELS = [100, 90, 70, 55, 40, 30, 20, 10, 5, 2, 1];

export const BUILTIN_ROLES = {
    guest: PERM.PERM_BASIC,
    default: PERM.PERM_DEFAULT,
    root: PERM.PERM_ALL,
};

export const DEFAULT_NODES = {
    'Explore / Khám phá': [
        { pic: 'qa', name: 'Q&A / Hỏi đáp' },
        { pic: 'share', name: 'Sharing / Chia sẻ' },
        { pic: 'solution', name: 'Solutions / Lời giải' },
    ],
    Hydro: [
        { pic: 'hydro', name: 'Hydro' },
        { name: 'Team / Đội nhóm' },
        { name: 'Monthly Contest / Cuộc thi hằng tháng' },
        { pic: 'advice', name: 'Suggestions / Góp ý' },
    ],
    'General / Chung': [
        { name: 'Math / Toán học' },
        { name: 'Programming / Lập trình' },
        { name: 'C' },
        { name: 'C++' },
        { name: 'Java' },
        { name: 'PHP' },
        { name: 'Python' },
        { name: 'Rust' },
        { name: 'ACM' },
    ],
};

export const CATEGORIES = {
    'Dynamic Programming': [
        'LCS',
        'LIS',
        'Knapsack',
        'Monotonic DP',
        'Circular DP',
        'Tree DP',
        'State Compression DP',
    ],
    Search: [
        'Enumeration',
        'Backtracking and Pruning',
        'Heuristic Search',
        'DLX',
        'Bidirectional Search',
        'Meet in the Middle',
        'Memoized Search',
        'Simulated Annealing',
    ],
    'Computational Geometry': [
        'Half-Plane Intersection',
        'Convex Hull',
        'Union and Intersection of Geometric Shapes',
        'Rotating Calipers',
        'Point Location',
        'Coordinate Transform',
        'Discretization and Sweep Line',
        'Inversion',
        'Voronoi Diagram',
        'Dual Graph of Planar Graph',
        'Triangulation',
        'Trapezoidal Decomposition',
        'Geometry Basics',
    ],
    Greedy: [],
    Tree: [
        'LCA',
        'Spanning Tree',
        'Second Minimum Spanning Tree',
        'DFS Order',
        'Binary Lifting',
        'Tree Divide and Conquer',
        'Heavy-Light Decomposition',
        'Link-Cut Tree',
    ],
    Graph: [
        'Floyd',
        'Dijkstra',
        'SPFA',
        'Negative Edge',
        'Planar Graph',
        'Bipartite Graph',
        'Bipartite Matching',
        'Shortest Path',
        'Difference Constraints',
        'Topological Sort',
        'Network Flow',
        'Strongly Connected Components',
        'Cut Vertex and Bridge',
        'Euler Circuit',
        '2-SAT',
    ],
    'Number Theory': [
        'Primality Test',
        'Euclidean Algorithm',
        'Diophantine Equation',
        'Digit DP',
        'Linear Congruence',
        'Baby-step Giant-step',
        'Pell Equation',
        'Large Integer Factorization',
        'Pythagorean Equation',
        'Multiplicative Function',
        'Fibonacci Sequence',
    ],
    Simulation: [],
    'Data Structure': [
        'Stack',
        'Queue',
        'Linked List',
        'Monotonic Queue',
        'Disjoint Set Union',
        'Heap',
        'Balanced Tree',
        'Segment Tree',
        'Binary Indexed Tree',
        'Tree of Trees',
        'Quadtree',
        'Partition Tree',
        'Merge Tree',
        'Scapegoat Tree',
        'Leftist Tree',
        'k-d Tree',
        'Block Linked List',
        'Hashing',
        'Functional Programming',
    ],
    'Game Theory': [
        'Bash Game',
        'Nim Game',
        'Wythoff Game',
        'Fibonacci Game',
        'Sprague-Grundy Theorem',
    ],
    String: [
        'KMP',
        'Suffix Data Structures',
        'Trie',
        'Aho-Corasick Automaton',
        'Manacher',
        'Expression Processing',
        'Minimal Representation',
    ],
    Combinatorics: [
        'Pigeonhole Principle',
        'Generating Function',
        'Inclusion-Exclusion',
        'Cantor Expansion',
        'Catalan Numbers',
        'Stirling Numbers',
        'Difference',
        'Polya Theorem',
    ],
    'Linear Algebra': [
        'Matrix Multiplication',
        'Gaussian Elimination',
        'Linear Programming',
    ],
    'High Precision': [
        'FFT',
    ],
    Recurrence: [],
    Probability: [
        'Randomization',
    ],
    NPC: [],
    Others: [
        'Binary Search',
        'Ternary Search',
        'Two Pointers',
        'Divide and Conquer',
        'Block Decomposition',
        'RMQ',
        'Fast Power',
        'Math',
        'Sorting',
        'Constructive',
        'Brute Force Table',
        'Bitwise Operation',
        'Discretization',
        'Mo Algorithm',
    ],
};

global.Hydro.model.builtin = {
    Permission,
    getScoreColor,
    PERM,
    PERMS,
    PERMS_BY_FAMILY,
    PRIV,
    LEVELS,
    BUILTIN_ROLES,
    DEFAULT_NODES,
    CATEGORIES,
    STATUS,
    STATUS_TEXTS,
    STATUS_SHORT_TEXTS,
    STATUS_CODES,
    NORMAL_STATUS,
    USER_GENDER_MALE,
    USER_GENDER_FEMALE,
    USER_GENDER_OTHER,
    USER_GENDERS,
    USER_GENDER_RANGE,
    USER_GENDER_ICONS,
};

